/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MatriculaRouteImport } from './routes/matricula'
import { Route as QualificacaoRouteImport } from './routes/qualificacao'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MatriculaRoute = MatriculaRouteImport.update({
  id: '/matricula',
  path: '/matricula',
  getParentRoute: () => rootRouteImport,
} as any)
const QualificacaoRoute = QualificacaoRouteImport.update({
  id: '/qualificacao',
  path: '/qualificacao',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/matricula': typeof MatriculaRoute
  '/qualificacao': typeof QualificacaoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/matricula': typeof MatriculaRoute
  '/qualificacao': typeof QualificacaoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/matricula': typeof MatriculaRoute
  '/qualificacao': typeof QualificacaoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/matricula' | '/qualificacao'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/matricula' | '/qualificacao'
  id: '__root__' | '/' | '/matricula' | '/qualificacao'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MatriculaRoute: typeof MatriculaRoute
  QualificacaoRoute: typeof QualificacaoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matricula': {
      id: '/matricula'
      path: '/matricula'
      fullPath: '/matricula'
      preLoaderRoute: typeof MatriculaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qualificacao': {
      id: '/qualificacao'
      path: '/qualificacao'
      fullPath: '/qualificacao'
      preLoaderRoute: typeof QualificacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MatriculaRoute: MatriculaRoute,
  QualificacaoRoute: QualificacaoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
